---
title: "Untitled"
author: "Casey O'Hara"
date: "11/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(git2r)
library(here)

```

# Clone all repos, count commits per person, render rmarkdown files

```{r}

### Create a GitHub credential file
cred <- cred_user_pass(username = 'oharac', password = 'pizzle9Dorf!')             
# You can also use a PAT, depends on your configuration

### Read-in all repo names
repos <- read_csv(here('asst_5_partners.csv'), skip = 2) %>%
  janitor::clean_names() %>%
  # CSV was created manually... but you can copy and paste all from GitHub at the same time.
  distinct() %>%
  gather(task, repo, ends_with('repo_link')) %>%
  mutate(dir = basename(repo),
         dir = str_remove(dir, '.git$'),
         dir = str_replace(dir, 'ej-screen', 'ejscreen'),
         dir = str_replace(dir, '--', '-'),
         dir = here('asst_5_repos', dir))

### Create directories, unless they already exist
if(any(!dir.exists(repos$dir))) {
  tmp <- lapply(repos$dir, dir.create)
}

### Clone repos, unless they have already been cloned
if(!any(map_lgl(repos$dir, is_empty))) {                                      # Not sure about this logical statement. Run manually?
  repos %>% head(30) %>% tail(1) %$%
    walk2(url, dirs, clone, credentials = cred)
}

## Look into each repo and find all rmd files
repos <- repos %>%
  mutate(files = list.files(main_path,
                            pattern = '*ej.Rmd|*grad.Rmd|enrollment.Rmd',        # Poor file naming...
                            recursive = T,                                       # Look in folders, sub folders, and sub sub fodlers...
                            full = T))                                           # Return the full absolute filepath

# Add a text file telling people that I will be grading them
notify <- function(dir){
  file <- file.path(dir, 'grading.txt')
  file.create(file)
  cat('You are now being graded!', file = file)
  add(repo = dir, 'grading.txt')
  commit(dir, message = 'You are now being graded')
  push(dir, credentials = cred)
}

safely_notify <- safely(notify)

notifications <- repos %$%
  map(dirs, safely_notify)

# General checks
## Who didn't store their rmd file in the src folder?
rmd_not_in_src <- repos %>%
  filter(!str_detect(files, 'src'))

######################## Task 1

## How many commit messages per user?
task_1_commits <- repos %>%
  filter(str_detect(dirs, 'ejscreen')) %>%                                        # Filter for task 1
  mutate(results = map(dirs, get_commits)) %>%                                    # Get commit history of each repo
  unnest(results) %>%                                                             # Format
  count(repo, user) %>%                                                           # Count individual commits
  filter(!user == 'GitHub')

## Did anyone have less than 2 commits?
less_than_2_t1 <- task_1_commits %>%
  filter(n < 2)

# Does it render?
safely_render <- safely(rmarkdown::render)

# Render task 1
results_task_1 <- repos %>%
  filter(str_detect(dirs, 'ejscreen')) %>%                                       # Filter for task 2
  mutate(run = map(files, safely_render, quiet = T, knit_root_dir = dirs)) %>%   # Safely render
  unnest_wider(run)                                                              # Unnest the weird list

######################### TASK 2

#Comments are same as above...

## How many commit messages per user?
task_2_commits <- repos %>%
  filter(str_detect(dirs, 'grad')) %>%
  mutate(results = map(dirs, get_commits)) %>%
  unnest(results) %>%
  group_by(repo, user) %>%
  count() %>%
  filter(!user == 'GitHub')

## Did anywone have less than 2 commits?
less_than_2_t2 <- task_2_commits %>%
  filter(n < 2)

## Does it render?
# Render task 2
results_task_2 <- repos %>%
  filter(str_detect(dirs, 'grad')) %>%
  mutate(run = map(files, safely_render, quiet = T)) %>%
  unnest_wider(run)


# Clean everything up (this deletes all repos!)
fs::dir_delete(repos$dirs)
1:31
1:32
To count the number of commits, I used these two short functions:
tabulize <- function(commit) {
  tibble::tibble(
    SHA  = commit$sha,
    user = commit$author$name,
    date = lubridate::as_datetime(commit$author$when$time)
  )
}

get_commits <- function(dir) {
  dir_commits <- git2r::commits(dir) %>%
    purrr::map_dfr(tabulize)
  return(dir_commits)
}
```

